baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Tesla'
theme = 'PaperMod'

[params]
  # PaperMod theme parameters
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
